[package]
name = "everpuzzle"
version = "0.1.0"
authors = ["Skytrias <skytrias@protonmail.com>"]

[dependencies]
amethyst = "0.9"
amethyst_input = "0.4.0"
rand = "*"

[features]
sdl_controller = [
    "amethyst_input/sdl_controller",
]